name: Run jest unit tests
on:
  pull_request:
    branches:
      - master
jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install --ignore-scripts
    - run: npm run test
